WebApp/WebApp/Areas/WebApi/Models/Album.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApp.Areas.WebApi.Models
{
    public class Album
    {
        public string artistName { get; set; }
        public string albumName { get; set; }
        public string trackName { get; set; }
        public Int32 trackCount { get; set; }
    }
}

WebApp/WebApp/Areas/WebApi/Controllers/SearchCompositionController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Http;
using WebApp.Areas.WebApi.Models;
using WebAppLibrary.Managers;
using WebAppLibrary.Models;

namespace WebApp.Areas.WebApi.Controllers
{
    public class SearchCompositionController : ApiController
    {        
        // GET: api/SearchComposition
        public IEnumerable<Album> Get(string executor, int searchSystemId = 1)
        {
            SearchServiceManager _ssmanager = new SearchServiceManager();
            SearchService _ss = _ssmanager.Get(searchSystemId);
            if (_ss == null)
            {
                _ss = new SearchService() { Name = "iTunes" };
                _ssmanager.Add(_ss);
            }

            AlbumRequestManager _armanager = new AlbumRequestManager();
            AlbumRequest _ar = _armanager.Get(executor);
            if (_ar == null)
            {
                _ar = new AlbumRequest() { Text = executor };
                _armanager.Add(_ar);
            }

            RequestManager _requestManager = new RequestManager(_ss);
            iTunesResponseManager _manager = new iTunesResponseManager();
            iTunesResponseCacheManager _cacheManager = new iTunesResponseCacheManager();
            List<iTunesResponse> response = new List<iTunesResponse>();

            try {
                string _response = _requestManager.GetResponse(executor);
                response = _manager.GetItunesResponseListFromJson(_response);
                _cacheManager.SaveToCache(_ar, _ss, response);
            }
            catch(WebException we)
            {
                response = _cacheManager.GetItunesResponseListFromCache(_ar, _ss);
            }            
            
            IEnumerable<Album> _albums = from track in response
                                         //where track.collectionName != null
                                         group track by track.collectionName ?? track.trackName into unicAlbums
                                         orderby unicAlbums.Key
                                         select new Album() { artistName = unicAlbums.First().artistName, albumName = unicAlbums.Key, trackName = unicAlbums.First().trackName, trackCount = unicAlbums.First().trackCount };
            return _albums;
            //return new string[] { "value1", "value2" };
        }

        // GET: api/SearchComposition/5
        public string Get(int id)
        {
            return "value";
        }

        // POST: api/SearchComposition
        public void Post([FromBody]string value)
        {
        }

        // PUT: api/SearchComposition/5
        public void Put(int id, [FromBody]string value)
        {
        }

        // DELETE: api/SearchComposition/5
        public void Delete(int id)
        {
        }
    }
}

WebApp/WebApp/Controllers/HomeController.cs
using System.Web.Mvc;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {    
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApp/WebApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApp/WebApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApp/WebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<label for="executorName">Введите исполнителя:</label>
<input type="text" placeholder="Название групы" id="executorName" />
<input type="button" value="Найти" data-bind="click: searchAlbums" id="searchButton" />

<table class="table table-striped">
    <thead>
        <tr data-bind="visible: showHeader">
            <th>Исполнитель</th>
            <th>Название альбома</th>
            <th>Композиция</th>
            <th>Количество треков</th>
        </tr>
    </thead>
    <tbody>
        <!-- ko foreach: albums -->
        <tr>
            <td data-bind="text: ArtistName"></td>
            <td data-bind="text: AlbumName"></td>
            <td data-bind="text: TrackName"></td>
            <td data-bind="text: TrackCount"></td>
        </tr>
        <!-- /ko -->
    </tbody>
</table>

@section scripts{
    <script src="~/Content/scripts/knockout-3.4.2.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            ko.applyBindings(new Albums());
        });

        var allAlbums = [];
        var updateAlbums;

        function Album(artistName, albumName, trackName, trackCount) {
            var self = this;

            this.ArtistName = artistName;
            this.AlbumName = albumName;
            this.TrackName = trackName;
            this.TrackCount = trackCount;
        }

        function Albums() {
            var self = this;

            // Editable catalog data - would come from the server
            self.albums = ko.observableArray(allAlbums);
            self.showHeader = ko.observable(self.albums().length > 0 ? true : false);

            self.searchAlbums = function(){
                loadData($("#executorName").val());
            };

            self.updateData = function () {
                //console.log("Update");
                self.albums(allAlbums);
                self.showHeader(self.albums().length > 0 ? true : false);
            };

            updateAlbums = self.updateData;
        }

        function loadData(name) {

            var url = '@Url.Action("Get", "SearchComposition", new { area = "WebApi" })';
            var parameters = {};
            parameters.executor = name;

            $.get(url, parameters, function (jsData) {
                if (jsData.length != undefined) {
                    //console.log(jsData);

                    fillAllAlbums(allAlbums, jsData);

                    updateAlbums();
                }
            });
        }

        function fillAllAlbums(parent, array) {
            parent.length = 0;
            for (item in array) {
                var _item = new Album(
                    array[item].artistName,
                    array[item].albumName == array[item].trackName ? "" : array[item].albumName,
                    array[item].trackName == array[item].albumName ? array[item].trackName : "",
                    array[item].trackCount
                );
                parent.push(_item);
            }
        }

    </script>
}

WebApp/WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("header", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("О программе", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>